import Foundation

struct ResumeSection: Identifiable, Codable, Equatable { let id: UUID; var title: String; var fields: [ResumeField]; var isVisible: Bool; var order: Int; init(id: UUID = UUID(), title: String, fields: [ResumeField], isVisible: Bool = true, order: Int) { self.id=id; self.title=title; self.fields=fields; self.isVisible=isVisible; self.order=order } }
struct ResumeField: Identifiable, Codable, Equatable { let id: UUID; var label: String; var value: String; var isBold: Bool; init(id: UUID = UUID(), label: String, value: String, isBold: Bool = false) { self.id=id; self.label=label; self.value=value; self.isBold=isBold } }
struct Resume: Identifiable, Codable, Equatable { let id: UUID; var name: String; var sections: [ResumeSection]; var templateID: UUID?; var lastModified: Date; init(id: UUID = UUID(), name: String, sections: [ResumeSection], templateID: UUID? = nil, lastModified: Date = Date()) { self.id=id; self.name=name; self.sections=sections; self.templateID=templateID; self.lastModified=lastModified }
    static let defaultResume = Resume(name:"Sri Yellela", sections:[
        ResumeSection(title:"Summary", fields:[ResumeField(label:"Profile", value:"Product-minded software engineer focused on mobile, automation, and human-centered workflow tools.")], order:0),
        ResumeSection(title:"Experience", fields:[ResumeField(label:"Draft", value:"Built a job-search and resume-tailoring platform with profile-aware matching.", isBold:true), ResumeField(label:"Mobile Prototype", value:"Designed native swipe interactions for queueing, saving, and applying to jobs.")], order:1),
        ResumeSection(title:"Education", fields:[ResumeField(label:"Northeastern University", value:"Graduate coursework in algorithms, computer vision, and software design.", isBold:true), ResumeField(label:"Focus", value:"Applied machine learning, systems design, and mobile product development.")], order:2),
        ResumeSection(title:"Skills", fields:[ResumeField(label:"Languages", value:"Swift, Java, Python, C++, JavaScript", isBold:true), ResumeField(label:"Frameworks", value:"SwiftUI, OpenCV, Android, Unity, SQLite")], order:3),
        ResumeSection(title:"Projects", fields:[ResumeField(label:"Draft", value:"Automated resume tailoring, ATS scoring, and job workflow management."), ResumeField(label:"Computer Vision Portfolio", value:"Face filters, recognition, calibration, and retrieval projects using OpenCV.")], order:4),
        ResumeSection(title:"Certifications", fields:[ResumeField(label:"Coursework", value:"CS5330 Pattern Recognition and Computer Vision; CS5800 Algorithms")], order:5)]) }
