import SwiftUI
struct SwipeCardModifier: ViewModifier { let enabled: Bool; let onSwipe: (SwipeAction)->Void; @GestureState private var dragOffset: CGSize = .zero; @State private var persistentOffset: CGSize = .zero; @State private var swipeAction: SwipeAction?; @State private var crossed = false
    func body(content: Content) -> some View { content.offset(x:persistentOffset.width+dragOffset.width,y:persistentOffset.height+dragOffset.height).rotationEffect(.degrees((persistentOffset.width+dragOffset.width)*SwipeThresholds.rotationFactor)).overlay(SwipeOverlayView(offset:CGSize(width:persistentOffset.width+dragOffset.width,height:persistentOffset.height+dragOffset.height), action:swipeAction)).gesture(enabled ? dragGesture : nil).animation(.cardReturn,value:dragOffset).animation(.cardThrow,value:persistentOffset) }
    private var dragGesture: some Gesture { DragGesture(minimumDistance:8).updating($dragOffset){v,s,_ in s=v.translation; update(v.translation)}.onChanged{update($0.translation)}.onEnded{finish($0)} }
    private func update(_ t: CGSize){ swipeAction = actionFor(t); if abs(t.width)>SwipeThresholds.softSwipeOffset && !crossed { crossed=true; HapticManager.shared.threshold() }; if abs(t.width)<=SwipeThresholds.softSwipeOffset { crossed=false } }
    private func actionFor(_ t: CGSize)->SwipeAction? { if t.width < -SwipeThresholds.softSwipeOffset { return .dislike }; if t.height < -SwipeThresholds.softSwipeOffset && abs(t.height)>abs(t.width) { return .skip }; if t.width > SwipeThresholds.hardSwipeOffset { return .apply }; if t.width > SwipeThresholds.softSwipeOffset && t.height < -50 { return .star }; if t.width > SwipeThresholds.softSwipeOffset { return .queue }; return nil }
    private func finish(_ v: DragGesture.Value){ let predicted=v.predictedEndTranslation; let velocity=hypot(predicted.width-v.translation.width,predicted.height-v.translation.height)*6; guard let action=actionFor(v.translation), velocity>SwipeThresholds.minimumVelocity || abs(v.translation.width)>SwipeThresholds.hardSwipeOffset || v.translation.height < -SwipeThresholds.hardSwipeOffset else { withAnimation(.cardReturn){persistentOffset=.zero; swipeAction=nil}; return }; let xSign: CGFloat = v.translation.width < 0 ? -1 : 1; withAnimation(.cardThrow){persistentOffset=CGSize(width:xSign*900,height:action == .skip ? -600 : v.translation.height*2)}; switch action { case .apply,.queue: HapticManager.shared.trigger(); case .star: HapticManager.shared.star(); case .dislike,.skip: HapticManager.shared.dismiss() }; DispatchQueue.main.asyncAfter(deadline:.now()+0.22){onSwipe(action); persistentOffset=.zero; swipeAction=nil; crossed=false} }
}
extension View { func swipeCard(enabled: Bool = true, onSwipe: @escaping (SwipeAction)->Void) -> some View { modifier(SwipeCardModifier(enabled:enabled,onSwipe:onSwipe)) } }
